### ISSUE TITLE
I do not have a rollover

### ISSUE THREAD

**Issue by franzellin** [ehelms/Tasks-Rollover-Chrome-Extension#2]
I downloaded the chrome version 1.1.6  but I do not notice any rollover of my tasks, I canceled and downladed again but the problem persists

I am surely making something wrong , I am using chrome 15.x on a Windows XP maschine 

I cannot act because I cannot manually rollover , I reload google tasks and google calendar but nothing changes

thanks for help - renato

**Comment by ehelms** [comment]
When you installed the extension - did it open a tab requesting access to the Google tasks API?

**Comment by franzellin** [comment]
yes, I granted acces

I never receive a notification telling me that it rolled over

The only notification that I receive is when I am off line , telling me that it could not access my tasks
  ----- Original Message -----

**Comment by ehelms** [comment]
All of the tasks you are expecting to rollover has or had a due date set on them?  

Could you open Wrench -> Tools -> Extensions, put it in developer mode, expand the Rollover Tasks extensions and open the html file at:
Inspect active views:   background.html

And see what errors are appearing in the console?

**Comment by franzellin** [comment]
ad1) I have DUE Date tasks, and 1 with the date of yesterday 09/nov2011 
I already tested a few days long 

ad2) I am in developer mode , and looking at background.html
I have 0 errors

I now  selected   select audits and reload  page  and audits on load  (20 of 20)  but still no errors
  ----- Original Message -----

**Comment by franzellin** [comment]
in developer kit, under NETWORK  I have a list  with all positions as 200 OK,
 the only strange thing is that after the "rollover.js"  position  ,
 there are  20 time TASKS  always with 200 OK

**Comment by franzellin** [comment]
and only 1 of 20   has size of 3.8KB  all the others are 0

**Comment by ehelms** [comment]
Let me work on getting some extra debugging output into a new version of the code to help us walk through it and figure out what might be the cause.  I have had others use the extension with success so I am curious what might be different.  Will probably take me a few days to find a little time to do that if you can bear with me.

**Comment by franzellin** [comment]
Surely, thanks for the time that you spend, but the product is so intelligent that we have to find the solution,  

I have my calendar displaying on the right side the TASKS, and reloading the calendar the position 10-November  2011 should be transformed in 11/November 2011 

and as already said, the only notification is when I am off-line, a rectangle bottom right telling that no tasks could be reached

  ----- Original Message -----

**Comment by ehelms** [comment]
If you take a task and move back its due date say - 5 days and then reload your calendar does it do anything?

**Comment by franzellin** [comment]
YES,  Roll Over success

**Comment by franzellin** [comment]
I live in europe and the date here is DD/MM/YYYY , perhaps this could be als a problem..

**Comment by ehelms** [comment]
Yep... I wondered if this might happen.  I tried my best to make the rollover timezone agnostic but working with dates in Javascript is a bit of a pain.  I will look into this more and see if I can't get a fix pushed out in the next few days.

**Comment by franzellin** [comment]
I congratulate first for the simple and intelligent Roll Over idea

the problem of the timezone you found it and I am sure you are going to solve it -  thanks - renato

**Comment by ehelms** [comment]
Renato,  

I pushed some changes to the date code that I hope will alleviate the timezone issues.  The extension should auto-update itself but if you would take a look and play around with it for me to let me know if they worked. Thanks.

**Comment by franzellin** [comment]
_I attached a screen shot of my calendar the 17 november at 10 a.m. Paris
time. the version is 1.18_
*
*
_as you can see in the tasks lists (rightside) I have 3 positions due
yesterday 16 Nov,  they were implemented the 15 november with due date the
16_
*
*
*all others are either perfectly rolled over *
*
*
*Theoretically these 3 positions should be also rolled over , but is not
bad, because today I see also the positions that I had to do yesterday *
*
*
*The only disadvantege is that these 3 positions do not appear in the 4
days view of my calendar but only in the tasks *
*
*
*Tomorrow I resend you the same screen shot *
*
*
*thanks
*
*
*
-   R e n a t o   F R A N Z E L L I N        saluti - regards - mfg -
  salutations  -  (g)*

On Thu, Nov 17, 2011 at 2:12 AM, Eric D Helms <
reply@reply.github.com

**Comment by ehelms** [comment]
Will you take the tasks that are out of place - set the due dates back say 3 or 4 days and then see what happens?

**Comment by franzellin** [comment]
_I send you 2 screen shots of my calendar in week form_
*
*
_1) first I added a new meeting tasks (lagrange telef) for the 7 december;
The program brings back to the 16 November (I tried 4 times and each time
was so)
*
*
*
*2) I modified the 2 tasks of  the 16 November with due date 12 and 13,
after refresh I received the rollover confirmation but I have now 3
positions on the 16 November (and disturbing is that one due for the 7
december)_
*
*
*
*
-   R e n a t o   F R A N Z E L L I N        saluti - regards - mfg -
  salutations  -  (g)*

On Thu, Nov 17, 2011 at 2:27 PM, Eric D Helms <
reply@reply.github.com

**Comment by ehelms** [comment]
Ahha! Good catch - that is an issue introduced with the changed code that I should be able to easily fix and push out - will post back once I do. For dates before the current date it appears to be rolling them over correctly now though by the sound of it?  Will post back once I push changes to prevent future due dates from rolling backwards.

**Comment by franzellin** [comment]
_I was looking at your file  "rollover.js",  and I would like to ask you 2
questions, I am not so good in java and I would like to understand:_
*
*
_line 37:  I suppose that you are asking if a duetask AND NOT  completed
 THEN  set the date as TODAY_
*
*
_I am asking myself  what happens if the duetask is scheduled in the future_
*
*
_line 40:  if  the date +1 is less then today (17 nov)   you make a rollover
*
*but if the date is the 16 of november (yesterday, you will never  roll)_
*
*
_why do you add 1, without adding, also the 16 november would be rolled
over to the 17_
*
*
*
*
_I would  ask: *
*IF the duedate is NOT completed AND is less then today THEN I would update
and all others not_
*
*
*
*
*
*
*
*
-   R e n a t o   F R A N Z E L L I N        saluti - regards - mfg -
  salutations  -  (g)*

On Thu, Nov 17, 2011 at 4:22 PM, Eric D Helms <
reply@reply.github.com

**Comment by ehelms** [comment]
Pushed changes that should prevent future tasks from being rolled back.  Let me know if you have any further issues. Thanks for the feedback.

**Comment by franzellin** [comment]
_No future tasks rolled back => ok_
*
*
*I send you a screen shot at saturday 08 a.m.19 November, where you can see
that 3 positions of thursday  17, are still there,  but it is not so
terrible
*
*
*
-   R e n a t o   F R A N Z E L L I N        saluti - regards - mfg -
  salutations  -  (g)*

On Sat, Nov 19, 2011 at 1:59 AM, Eric D Helms <
reply@reply.github.com

**Comment by franzellin** [comment]
*I send you the new screenshot at 5PM  and I had a roll over, the 3
positions that this morning were with due date 17 november , are now with
due date 18 november, it means that the roll over happened
*
*
*
-   R e n a t o   F R A N Z E L L I N        saluti - regards - mfg -
  salutations  -  (g)*

**Comment by franzellin** [comment]
_as you can see today, sunday the 20 november at 6 PM european time, I have
still 3 positions with due date friday 18_
*
*
*and I do not understand why...
*
*
*
-   R e n a t o   F R A N Z E L L I N        saluti - regards - mfg -
  salutations  -  (g)*

**Comment by franzellin** [comment]
*as you can see, today  monday 21 november at 3pm europe time, I have still
no rollover of 3 friday positions
*
*
*
-   R e n a t o   F R A N Z E L L I N        saluti - regards - mfg -
  salutations  -  (g)*

**Comment by ehelms** [comment]
I am seeing some strange issues occurring with mine as well all of a sudden.  Will look in to it more.  I have an idea why you are seeing the behavior you are - will see if I can fix it in the next few days.

**Comment by franzellin** [comment]
*thanks
*
*
*
-   R e n a t o   F R A N Z E L L I N        saluti - regards - mfg -
  salutations  -  (g)*

On Mon, Nov 21, 2011 at 8:16 PM, Eric D Helms <
reply@reply.github.com

**Comment by franzellin** [comment]
*I imagine that shopping was the task of the weekend, but I remember you
that the roll over is waiting for a  1.2.2 version...
*
*
*
-   R e n a t o   F R A N Z E L L I N        saluti - regards - mfg -
  salutations  -  (g)*

**Comment by franzellin** [comment]
*I updated chrome to  15.0.874.121 m  and I have the sensation that your
extension is blocked because inspecting the popup i cannot see your files
anymore
*
*
*
-   R e n a t o   F R A N Z E L L I N        saluti - regards - mfg -
  salutations  -  (g)*

**Comment by ehelms** [comment]
Been bogged down with the holidays - my tasks rollover is having issues as well so I will look in to this.

**Comment by franzellin** [comment]
*no problem
*
*
*
-   R e n a t o   F R A N Z E L L I N        saluti - regards - mfg -
  salutations  -  (g)*

On Wed, Nov 30, 2011 at 17:17, Eric D Helms <
reply@reply.github.com

**Comment by ehelms** [comment]
Renato - will you check to make sure your extension updates to 1.2.2 and let me know if you see any more abnormalities?  I fixed a typo and issue that caused tasks off by a year to be rolled back.

**Comment by franzellin** [comment]
*ok
*
*
*
-   R e n a t o   F R A N Z E L L I N        saluti - regards - mfg -
  salutations  -  (g)*

On Tue, Dec 6, 2011 at 16:51, Eric D Helms <
reply@reply.github.com

**Comment by franzellin** [comment]
_1) The new version works again and it is a pleasure_
*
*
_2) the only "mistake" is as you can see in the attached screenshot that
the "TEST"  position was rolled over  from monday to tuesday, and the
tuesday positions (all the others) stayed on tuesday._
*
*
_I checked and the local time in California is already Wednesday, tomorrow
we can see if the tuesday positions are rolled over either to Wednesday or
Thursday_
*
*
_My sensation is that probably the roll over  date is  "today -1"   instead
of "today", but tomorrow *
*will know it exactly_
*
*
_On a general point of view, is  not bad to have all rolled over positions
on the day before, because shows you exactly what you missed, the annoing
point is that Google Calendar in the "Agenda view or Day View" does not
show the "yesterday" and I am obliged to use the "week view"  to see all of
them_
*
*
_Let us wait till tomorrow I resend you my calendar_
*
*
_bravo_
*
*
*
*
*
*
*
*
*
*
*
*
-   R e n a t o   F R A N Z E L L I N        saluti - regards - mfg -
  salutations  -  (g)*

**Comment by franzellin** [comment]
Looking in rollover.js , I am asking myself what happens if you change the
actual line 41

if( ((taskDate.getDate() + 1) < today.getDate()  *
*
*
*
_with                                  =< today.getdate()_
*
*
_because  making an example  a  task with duedate  "6"   ==>   6+1 = 7
and 7  is not  < than today(7) and automatically the "6" positions are not
rolled over_
-  *
  *
  *
-   R e n a t o   F R A N Z E L L I N        saluti - regards - mfg -
  salutations  -  (g)*

**Comment by franzellin** [comment]
_the roll over was successful_
*
*
_the tuesday's events were rolled at wednesday, as I told you before, they
are at "TODAY-1"_
*
*
*as you can see I  am using in google calendar the "week" view *
*
*
*Please think about to test once  in rollover .js the (  <=  )  modification
*
*
*
*
*
-   R e n a t o   F R A N Z E L L I N        saluti - regards - mfg -
  salutations  -  (g)*

**Comment by franzellin** [comment]
_as you can see it rolls  (today-1)   *
*
*
*more I think about, it is probably the best solution to have the rolled
positions at -1, because we can identify them perfectly_
*
*
_thanks_
*
*
*
*
*
*
-   R e n a t o   F R A N Z E L L I N        saluti - regards - mfg -
  salutations  -  (g)*

**Comment by ehelms** [comment]
I am starting to wonder if this is related to Greenwich meantime.  The reason I have the -1 in the code when setting the day is that I noticed that was the only way to set the date properly and get tasks to appear on the correct date.  I will have to dig in to this more to see if there is a mismatch there due to timezones and see if I can correct it depending on location.

**Comment by franzellin** [comment]
I am now, quite happy with the actual solution, because I know that all -1 positions are rolledover and the actuals are really "fresh"

also in this form your application is 5stars worth

  ----- Original Message -----

**Comment by franzellin** [comment]
I found out that  clicking on the small calendar in google calendar, I can display a range of days as I wish,  for instance displaying also "yesterday".

the agenda or custom view begins always with "today"

with this trick your application is perfect as it is now  and does not need any changement and all rolledover positions are under "yesterday"

**Comment by franzellin** [comment]
Messaggio

```
                                                                  A U G U R I 
```

 R E N A T O_ F R A N Z E L L I N _ Salutations _ mfg _ Saluti _ Regards_ (mc)
