### ISSUE TITLE
Roll over failed notification is annoying

### ISSUE THREAD

**Issue by bmbouter** [ehelms/Tasks-Rollover-Chrome-Extension#3]
Google changes their Tasks API a lot (or they have reliability problems, I'm not sure which).  Either way for hours at a time every so often I will get a "Tasks could not be rolled over" or some similar error message.  Since I look at my calendar all the time I can tell pretty obviously if tasks haven't rolled over.  I wish this message was never shown.  It could be a setting, but I would just remove it all together since I don't know who would find this useful.

The error also occurs when I have no internet which is annoying on planes.

**Comment by ehelms** [comment]
This should be fixed with the newest version.  Failures are now silent.
