### ISSUE TITLE
End of year bug

### ISSUE THREAD

**Issue by bmbouter** [ehelms/Tasks-Rollover-Chrome-Extension#4]
I had tasks existing on the date of 12/31/2011.  Today (1/2/2012) I noticed that they don't roll over.  I received no error messages, yet the tasks don't roll over.  I also manually told them to roll over using the button the extension provides.

**Comment by ehelms** [comment]
fd7a26bc6f254efdaf7f7b9cd4249054eef53eb9

All tasks should rollover from the New Year.
